### PR TITLE
Enhancements and bug fixes

### LINKED ISSUE #20: Add a way to modify the target url before doing the redirection
## The problem to solve

We would need a way to modify the target url before the redirection is done by the module.
Our use case is that we want to perform at once a potential domain redirection along with a path redirect coming from the module (or a regex based if the is no match in the pieces).

## Proposed solution

As a proposed solution, we can emit another event like `beforeRedirect` that would transmit the target url as resolved by the module, and then get back the url that may have been modified, just like we do some kind of with the `noMatch` event.

### LINKED ISSUE #21: SEO Fields are displayed with @apostrophecms/seo
## To Reproduce

On a project with `@apostrophe-cms/seo` module, when editing a redirect piece, we have the SEO panel.

## Expected behavior
By default, it should not be the case

## Describe the bug
Bad option name in the module default options (`seo: false` instead of `seoFields: false`)

### LINKED ISSUE #22: ignoreQueryString option not taken into account
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce
The ignoreQueryString functionality is not working.

## Expected behavior
If set I set yes, I should expect the query string to be ignored, the redirect should happen whatever query string in the source url.

## Describe the bug
The field is missing in the projection when we find the pieces.

### LINKED ISSUE #23: Error when using internal page
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

When the redirection targets an internal page, we are unable to save correctly the piece (it saves only the draft).
There is a 500 error when trying to save the published version due to missing `aposLocale` field in the internal page document.

## Expected behavior
We should be able to setup a redirect to an internal page.

## Describe the bug
By adding `aposLocale` in the projection of `_newPage` it works.

### LINKED ISSUE #24: Performance: execute the middleware as soon as possible
## The problem to solve

The `checkRedirect` middleware should be executed as soon as possible, before any other middleware like `@postrophecms/global` in order to do the redirection before any other heavy computation that is not needed in case of a redirect.

## Proposed solution

Execute the middleware before `@apostrophecms/global` one.

### LINKED ISSUE #25: Do not check for redirect for technical pages like api/v1/*
## The problem to solve

For performance globally, the middleware should not to try to find a redirect when an url is a technical one.

## Proposed solution

Add an option `regExpWhiteList` in the module as an array of RegExp, with one default value `/\/api\/v1\/.*/`.
If the incoming url match one of those regexp, we don't check for redirect pieces, we go `next()`.

### LINKED ISSUE #26: Add a forwardQueryString field
## The problem to solve

Currently we have no option to tell a redirect piece that it should forward the incoming query string.

## Proposed solution

Add a field in the schema in order to give the capacity to the editor to tell that if there is a query string on source url, we should forward it to the target url.

### PR DESCRIPTION
**Pull request by daklik**
Closes #26 
Closes #25 
Closes #24 
Closes #23 
Closes #22 
Closes #21 
Closes #20

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -16,7 +16,9 @@ module.exports = {
       browser: true
     },
     openGraph: false, // Disables @apostrophecms/open-graph for redirects
-    seo: false // Disables @apostrophecms/seo for redirects
+    seoFields: false, // Disables @apostrophecms/seo for redirects
+    regExpWhiteList: [ /\/api\/v1\/.*/ ],
```
Comment (boutell) [inline index.js:20]: We use `allowList` by convention, I'll take care of it after merging.

**Review by boutell — APPROVED** [review]
Thank you!
